# Colors
FRAME_COLOR = "#151515"
BG_COLOR = "#1e1e1e"
HEADING_COLOR = "#6C7BFE"
BUTTON_SELECTION_COLOR = "#6C7BFE"
DELETE_COLOR = "#ff6666"
GRAY = "#ABB2B9"


# Spacing and sizes
FRAME_BORDER = 0
HEADING_SIZE = 24


