# Light

LIGHT_BG_COLOR = "#FFFFFF"
LIGHT_FRAME_COLOR = "#FFFAFA"
LIGHT_TEXT_COLOR = "#000000"
LIGHT_HEADING_COLOR = "#78586f"
LIGHT_BUTTON_COLOR = "#7F8DAD"

# Dark
DARK_BG_COLOR = "#1e1e1e"
DARK_FRAME_COLOR = "#151515"
DARK_TEXT_COLOR = "#FFFFFF"
DARK_HEADING_COLOR = "#6C7BFE"
DARK_BUTTON_COLOR = "#6C7BFE"

# Tokyo City Darker
SOLARIZED_BG_COLOR = "#181C24"
SOLARIZED_FRAME_COLOR = "#181C24"
SOLARIZED_TEXT_COLOR = "#FFFFFF"
SOLARIZED_HEADING_COLOR = "#e45e91"
SOLARIZED_BUTTON_COLOR = "#14a5ae"